= Home Assistant stuff
:experimental:
:icons: font
:toc: preamble
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
endif::[]

A collection of Home Assistant blueprints, scripts…

'''

== Blueprints

=== IKEA TRÅDFRI 5 buttons remote

This blueprint is based on
https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_5button_remote_white.yaml[this one,window=_blank],
by https://community.home-assistant.io/u/niro1987/summary[niro1987, window=_blank]

[link=https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2Fjljouannic%2Fmy-ha%2Fblob%2Fmain%2Fblueprints%2Fzha_ikea_tradfri_5button_remote_white.yaml]
image::https://my.home-assistant.io/badges/blueprint_import.svg[Home Assistant import button for IKEA TRÅDFRI 5 buttons remote blueprint]

=== Wiser 4 buttons wall remote

This blueprint is a fixed version of https://gist.github.com/probize/5a9cfb3fadac5e7955942b0bfe841238[this one, window=_blank],
by https://community.home-assistant.io/u/probize/summary[Probize,window=_blank]

[link=https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2Fjljouannic%2Fmy-ha%2Fblob%2Fmain%2Fblueprints%2Fzha-Wiser-4-button-remote.yaml]
image::https://my.home-assistant.io/badges/blueprint_import.svg[Home Assistant import button for Wiser 4 buttons wall remote blueprint]

NOTE: According to
https://community.home-assistant.io/t/elko-smart-4-button-switch-setup/425226/2[this comment,window=_blank],
the remote 2-channel mode is activated by pressing button 1 and 4 for 10 seconds.

== Scripts

=== Configure Lixee reporting frequency

I used this script after my Lixee ZLinky_TIC started to report less often (about only twice a month!).

NOTE: link:https://github.com/mdeweerd/zha-toolkit[ZHA Toolkit,window=_blank] must be installed for this script to operate as expected.
