alias: Configure Lixee Reporting to 1Wh change and max 5 minutes
sequence:
  - variables:
      ieee: "{{(device_attr(device, 'identifiers')|list)[0][1]}}"
      default_tries: 3
  - action: zha_toolkit.conf_report
    alias: Set report config for tiers 1
    data:
      ieee: "{{ ieee }}"
      cluster: 1794
      attribute: 256
      min_interval: 1
      max_interval: 300
      tries: "{{ default_tries}}"
      reportable_change: 1
      event_done: zha_done
  - action: zha_toolkit.conf_report_read
    alias: Read report config for tiers 1 (allows verification)
    data:
      ieee: "{{ ieee }}"
      cluster: 1794
      attribute: 256
      tries: "{{ default_tries}}"
      event_done: zha_done
  - action: zha_toolkit.conf_report
    data:
      ieee: "{{ ieee }}"
      cluster: 1794
      attribute: 258
      min_interval: 1
      max_interval: 300
      tries: "{{ default_tries}}"
      reportable_change: 1
      event_done: zha_done
    alias: Set report config for tiers 2
  - action: zha_toolkit.conf_report_read
    alias: Read report config for tiers 2 (allows verification)
    data:
      ieee: "{{ ieee }}"
      endpoint: 1
      cluster: 1794
      attribute: 258
      tries: "{{ default_tries}}"
      event_done: zha_done
  - action: zha_toolkit.conf_report
    alias: Active power report configuration
    data:
      ieee: "{{ ieee }}"
      endpoint: 1
      cluster: 2820
      attribute: 1291
      min_interval: 1
      max_interval: 300
      tries: "{{ default_tries}}"
      reportable_change: 1
      event_done: zha_done
    enabled: false
  - action: zha_toolkit.conf_report_read
    alias: Active power report configuration read back
    data:
      ieee: "{{ ieee }}"
      cluster: 2820
      attribute: 1291
      tries: "{{ default_tries}}"
      event_done: zha_done
    enabled: false
  - action: zha_toolkit.conf_report
    alias: Mains voltage report configuration
    data:
      ieee: "{{ ieee }}"
      cluster: 1
      attribute: 0
      min_interval: 1
      max_interval: 3900
      tries: "{{ default_tries}}"
      reportable_change: 1
      event_done: zha_done
    enabled: false
  - action: zha_toolkit.conf_report_read
    alias: Mains voltage report configuration read back
    data:
      ieee: "{{ ieee }}"
      cluster: 1
      attribute: 0
      tries: "{{ default_tries}}"
      event_done: zha_done
    enabled: false
fields:
  device:
    name: Lixee
    description: Lixee ZLinky device to configure
    required: true
    selector:
      device:
        filter:
          manufacturer: LiXee
          model: ZLinky_TIC
        entity:
          integration: zha
mode: single
icon: mdi:home-lightning-bolt-outline
